#ifndef types_h
#define types_h

//----------------------------------------------


typedef   unsigned char       byte  ;
typedef   unsigned short      word  ;
typedef   unsigned long int  lword  ;

typedef     signed char      sbyte  ;
typedef     signed short     sword  ;
typedef     signed long int slword  ;

typedef   const               c  ;
typedef   double              d  ;
typedef   unsigned char       b  ;
typedef   unsigned short      w  ;
typedef   unsigned long int  lw  ;

typedef     signed char      sb  ;
typedef     signed int       sw  ;
typedef     signed long int slw  ;

//컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴

#endif