#ifndef _f_zapoln_h
#define _f_zapoln_h

#define  mInit_Fzapoln()

#define  mSet_Fzapoln1( Low, High )
#define  mSet_Fzapoln2( Low, High )

#define  mFzapoln1_start()
#define  mFzapoln2_start()


#define  mFzapoln1_stop()
#define  mFzapoln2_stop()

#define  mSet_Fzapoln( Low, High )
#define  mFzapoln_start()
#define  mFzapoln_stop()

#define  mInit_Fzapoln3()

#define  mSet_Fzapoln3( Low, High )
#define  mFzapoln3_start()
#define  mFzapoln3_stop()

#define  mInit_Fzapoln4()
#define  mSet_Fzapoln4( Low, High )
#define  mFzapoln4_start()
#define  mFzapoln4_stop()

#define  mFzapoln_strob_set( data )

#endif
