[2J

    Введите, пожалуйста, принятое в Вашей программе значение 
  (в дискретах) соответствующее номинальному току используемому
  для теплового расчета: 
 значение соответствующее номинальному току
 составляет 200.00   дискрет ?! ... хорошо.
  Введите, пожалуйста, количество элементов токово-временной таблицы :    5 элементов ?! ... хорошо,
теперь введите, пожалуйста, токово-временную таблицу
(по убывающей в зависимости от тока) :
ее  1-й элемент: ток (в номиналах)  -            время (сек) - 
 ток = 2.25     * Iном   , а время = 10.00    сек ?! ... хорошо,
ее  2-й элемент: ток (в номиналах)  -            время (сек) - 
 ток = 2.00     * Iном   , а время = 15.00    сек ?! ... хорошо,
ее  3-й элемент: ток (в номиналах)  -            время (сек) - 
 ток = 1.75     * Iном   , а время = 60.00    сек ?! ... хорошо,
ее  4-й элемент: ток (в номиналах)  -            время (сек) - 
 ток = 1.50     * Iном   , а время = 120.00   сек ?! ... хорошо,
ее  5-й элемент: ток (в номиналах)  -            время (сек) - 
 ток = 1.05     * Iном   , а время = 7200.00  сек ?! ... хорошо,.

   Введите, пожалуйста, требуемое время охлаждения после нагрева до
 макс. значения (сек): 
 время охлаждения составляет 420.00   сек ?! ... хорошо.

   Введите, пожалуйста, период цикла прозводимого Вашей программой
  теплового перерасчета (сек) :  
  период цикла перерасчета составляет 0.02     сек ?! ... хорошо.

  Результаты расчета:
  I =      2.25   tau =    272.75  Kq =  0.000073 (0.000004cfh) 
  I =      2.00   tau =    325.78  Kq =  0.000061 (0.00000406h) 
  I =      1.75   tau =    969.69  Kq =  0.000021 (0.0000015bh) 
  I =      1.50   tau =   1272.39  Kq =  0.000016 (0.00000108h) 
  I =      1.05   tau =   3126.92  Kq =  0.000006 (0.0000006ch) 

  (для охлаждения)  tau =    182.40  Kq =  0.000110 (0.0000072fh)


   РАБОЧИЙ ФАЙЛ < #TEPLO.H > СФОРМИРОВАН !

   РАБОТА ПРОГРАММЫ ЗАВЕРШЕНА !

   ПРЕДУПРЕЖДЕНИЙ:      0.

